---
title: "final_presentation_EDA"
author: "Connor Mignone"
date: "9/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
```

```{r}
data_oversampling <- read_csv("../data/data_oversampling.csv")
View(data_oversampling)
# final data with no balance correction
data_original_sampling <- read_csv("../data/final/data_original_sampling.csv")
View(data_original_sampling)
```

Showing the difference in data using oversampling techniques
```{r}
ggplot_ovs <- data_oversampling
ggplot_ovs$y_bin <- case_when(ggplot_ovs$y_bin == 1 ~ "Admit Patient", ggplot_ovs$y_bin == 0 ~ "Discharge Patient")

ggplot_os <- data_original_sampling
ggplot_os$y_bin <- case_when(ggplot_os$y_bin == 1 ~ "Admit Patient", ggplot_os$y_bin == 0 ~ "Discharge Patient")
ggplot(data = ggplot_os)+
  geom_bar(aes(as.factor(y_bin)))+
  labs(title = "Original Sampling Data", x = "Doctor Decision")+
  theme_classic()

ggplot(data = ggplot_ovs)+
  geom_bar(aes(as.factor(y_bin)))+
  labs(title = "Oversampled Data", x = "Doctor Decision")+
  theme_classic()
```


Age Quantile Admitted VS Discharged 
```{r}
ggplot(data = ggplot_os)+
    geom_histogram(aes(`Patient age quantile`), bins = 15)+
  facet_wrap(vars(y_bin))+
  labs(x = "Patient Age Quantile", y = "Number of Patients")+
  theme_bw()
```

```{r}
ggplot(data = ggplot_os)+
    geom_histogram(aes(`Platelets`), bins = 10)+
  facet_wrap(vars(y_bin))+
  labs(title = "Admitted vs. Discharged Patient Platelet Distribution", x = "Normalized Platelet Test Result", y = "Number of Patients")
```

```{r}
ggplot(data = ggplot_os)+
    geom_histogram(aes(`Hb saturation (venous blood gas analysis)`), bins = 10)+
  facet_wrap(vars(y_bin))+
  labs(title = "Admitted vs. Discharged Patient Lymphocyte Distribution", x = "Normalized Platelet Test Result", y = "Number of Patients")
```

```{r}
ggplot(data = ggplot_os)+
    geom_bar(aes(as.factor(num_virus_or_bacteria_dectected)))+
  facet_wrap(vars(y_bin))+
  labs(title = "Admitted vs. Discharged Patient Virus Test Distribution", x = "Number of Other Viruses or Bacteria Dectected", y = "Number of Patients")
```


```{r}
ggplot(data = ggplot_os)+
    geom_histogram(aes(Eosinophils), bins = 15)+
  facet_wrap(vars(y_bin))+
  labs(title = "Admit vs. Discharge Patient Eosinophils Distribution", x = "Eosinophils", y = "Number of Patients")+ 
  theme(plot.background = element_rect(fill = "#f9f9f9"),
        
         panel.background = element_rect(fill = "#ceeaf5",
                                        colour = "#0e4776",
                                        size = 2,
                                        linetype = "solid"),
        
        title = element_text(color = "#0e4776", size = 15),
   
        panel.grid.major = element_line(size = 0.5,
                                        linetype = 'solid',
                                        colour = "white"), 
        strip.text.x = element_text(size = 12, color = "#F5AD9A", face = "bold"),
        
        strip.background.x = element_rect(fill = "#0e4776"),
  
        panel.grid.minor = element_line(size = 0.25, 
                                        linetype = 'solid',
                                        colour = "white"))
#0e4776
```



```{r}
ggplot(data = ggplot_os)+
    geom_bar(aes(as.factor(blood_test_grp)))+
  facet_wrap(vars(y_bin))+
  labs(title = "Admit vs. Discharge Patient Blood Test", x = "Blood Test Taken", y = "Number of Patients")+ 
  theme(plot.background = element_rect(fill = "#f9f9f9"),
        
         panel.background = element_rect(fill = "#ceeaf5",
                                        colour = "#0e4776",
                                        size = 2,
                                        linetype = "solid"),
        
        title = element_text(color = "#0e4776", size = 15),
   
        panel.grid.major = element_line(size = 0.5,
                                        linetype = 'solid',
                                        colour = "white"), 
        strip.text.x = element_text(size = 12, color = "#F5AD9A", face = "bold"),
        
        strip.background.x = element_rect(fill = "#0e4776"),
  
        panel.grid.minor = element_line(size = 0.25, 
                                        linetype = 'solid',
                                        colour = "white")
        )
#0e4776
```


```{r}
ggplot(data = ggplot_os)+
    geom_jitter(aes(x=Sodium, y = Potassium, color = y_bin),)+
  labs(title = "Sodium vs. Potassium Levels", x = "Sodium", y = "Potassium", color = "Admit vs. Discharge")+ 
  theme(plot.background = element_rect(fill = "#f9f9f9"),
        
         panel.background = element_rect(fill = "#ceeaf5",
                                        colour = "#0e4776",
                                        size = 2,
                                        linetype = "solid"),
        
        title = element_text(color = "#0e4776", size = 15),
   
        panel.grid.major = element_line(size = 0.5,
                                        linetype = 'solid',
                                        colour = "white"), 
        strip.text.x = element_text(size = 12, color = "#F5AD9A", face = "bold"),
        
        strip.background.x = element_rect(fill = "#0e4776"),
  
        panel.grid.minor = element_line(size = 0.25, 
                                        linetype = 'solid',
                                        colour = "white"),
        legend.text = element_text(size = 9),
        legend.title = element_text(size= 10))
#0e4776
```



```{r}
ggplot(data = ggplot_os)+
    geom_boxplot(aes(x=y_bin, y= Sodium))+
  geom_jitter(aes(x = y_bin, y = Sodium, color = as.logical(pot_sod_grp)), size = 2.5, alpha = .3)+
  labs(title = "Sodium Levels", x = "Doctor Deicison", y = "Sodium", color = "Salt Test Taken")+ 
  theme(plot.background = element_rect(fill = "#f9f9f9"),
        
         panel.background = element_rect(fill = "#ceeaf5",
                                        colour = "#0e4776",
                                        size = 2,
                                        linetype = "solid"),
        
        title = element_text(color = "#0e4776", size = 15),
   
        panel.grid.major = element_line(size = 0.5,
                                        linetype = 'solid',
                                        colour = "white"), 
        strip.text.x = element_text(size = 12, color = "#F5AD9A", face = "bold"),
        
        strip.background.x = element_rect(fill = "#0e4776"),
  
        panel.grid.minor = element_line(size = 0.25, 
                                        linetype = 'solid',
                                        colour = "white"),
        legend.text = element_text(size = 9),
        legend.title = element_text(size= 10))
#0e4776

```



```{r}
ggplot(data = ggplot_os)+
    geom_boxplot(aes(x=y_bin, y= Potassium,))+
  geom_jitter(aes(x = y_bin, y = Potassium, color = as.logical(pot_sod_grp)), size = 2.5, alpha = .3)+
  labs(title = "Potassium Levels", x = "Doctor Deicison", y = "Potassium", color = "Salt Test Taken")+ 
  theme(plot.background = element_rect(fill = "#f9f9f9"),
        
         panel.background = element_rect(fill = "#ceeaf5",
                                        colour = "#0e4776",
                                        size = 2,
                                        linetype = "solid"),
        
        title = element_text(color = "#0e4776", size = 15),
   
        panel.grid.major = element_line(size = 0.5,
                                        linetype = 'solid',
                                        colour = "white"), 
        strip.text.x = element_text(size = 12, color = "#F5AD9A", face = "bold"),
        
        strip.background.x = element_rect(fill = "#0e4776"),
  
        panel.grid.minor = element_line(size = 0.25, 
                                        linetype = 'solid',
                                        colour = "white"),
        legend.text = element_text(size = 9),
        legend.title = element_text(size= 10))
#0e4776

```

